all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
- - 25
- - 26
- - 27
- - 28
- - 29
- - 30
- - 31
- - 32
- - 33
- - 34
- - 35
- - 36
- - 37
- - 38
- - 39
- - 40
- - 41
- - 42
- - 43
- - 44
- - 45
- - 46
- - 47
all_joints_names:
- nose
- rightEar
- leftEar
- head
- neck
- center
- hip
- tailBase
- RfrontPaw
- LfrontPaw
- RrearPaw
- LrearPaw
- foodPlate
- foodPellet1
- foodPellet2
- frontTopHouse
- frontBottomHouse
- backTopHouse
- backBottomHouse
- centerHouse
- centerBackHouse
- upMothTop
- upMothBottom
- upMothWingRight
- upMothWingLeft
- downMothTop
- downMothBottom
- downMothWingRight
- downMothWingLeft
- upWormHead
- upWormCenter
- upWormTail
- downWormHead
- downWormCenter
- downWormTail
- blackCricket
- blackSwoop
- blackLoom
- yellowCricket
- yellowSwoop
- greyLoom
- flash
- cornerTopL
- cornerTopR
- cornerBottomL
- cornerBottomR
- windowTop
- windowBottom
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_TwoMiceTrialsNov20/TwoMiceTrials_Thais95shuffle1.mat
dataset_type: default
decay_steps: 30000
display_iters: 1000
global_scale: 0.8
init_weights: /users/tdelros1/anaconda/dlc_env/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_TwoMiceTrialsNov20/Documentation_data-TwoMiceTrials_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 48
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /gpfs/home/tdelros1/TwoMiceTrials-Thais-2022-11-20
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
